### PR TITLE
Fix invalid java interop call

### PR DESCRIPTION
**Pull request by ducky427**

### CODE REVIEW

**Comment by tomekw** [comment]
Oh :( Thanks @ducky427! Is it easy to add a test case for this? /cc @yogthos

**Comment by ducky427** [comment]
@tomekw, actually this call has been deprecated and it literally does [nothing](https://github.com/openbouquet/HikariCP/blob/master/src/main/java/com/zaxxer/hikari/HikariConfig.java#L443).  So it may be worth removing it.

**Comment by tomekw** [comment]
So this https://github.com/tomekw/hikari-cp/pull/58/files is not needed? @yogthos @ducky427 hmm - is there a way to solve it somehow? (I can't check it now)

**Comment by yogthos** [comment]
My bad not checking if I was used in the latest hikari version. The issue I ran into was using JTDS driver which doesn't support the connection test. Since the option is deprecated it would make sense to remove it.

**Comment by ducky427** [comment]
Cool, so can we just revert https://github.com/tomekw/hikari-cp/pull/58/files?

**Comment by yogthos** [comment]
Yeah I think so, sorry about this one.

**Comment by ducky427** [comment]
Please see #61

**Pull request closed without merging**
