### PR TITLE
add a general purpose way to alter Hikari config

### PR DESCRIPTION
**Pull request by MichaelBlume**
for options not currently supported by hikari-cp, for example setConnectionInitSql

### CODE REVIEW

**Comment by tomekw** [comment]
Thank you @MichaelBlume, I will try to look into this later today!

**Comment by ikitommi** [comment]
hi guys.

was just thinking about PR'n at least the setConnectionInitSql (using it now), maybe all supported confs, would work also with external &/ edn-based configs.

Is the `configure` really needed? As this works already:

```clj
(let [datasource (HikariDataSource.
                   (doto (hikari/datasource-config (dissoc config :extras))
                     (.setConnectionInitSql (-> config :extras :connection-init-sql))))]
  ...))
```

**Comment by ikitommi** [comment]
also, having a helper-fn like 

```clj
(defn ->HikariDataSource [config] (HikariDataSource. config))
``` 
would help as one could do the previous example without having to do any imports:

```clojure
(require '[hikari-cp.core :as hikari])

(def config 
  {:adapter "postgresql"
   ...
   :extras {:connection-init-sql "set SESSION paha.peikko = ''"}})

(let [datasource (hikari/->HikariDataSource
                   (doto (hikari/datasource-config (dissoc config :extras))
                     (.setConnectionInitSql (-> config :extras :connection-init-sql))))]
  ...))
```

as "pretty" as the java-interop gets... ;)

**Comment by jstepien** [comment]
Hi! I like @MichaelBlume's approach. It reminds me of transforming functions you can pass when initialising an Aleph server. Here's the [interface][int] and here's the [implementation][imp]. It's flexible and doesn't expose any extra public vars.

[int]: https://github.com/ztellman/aleph/blob/df1cee3c4233c05fb27af62e9e2844bf453c70a9/src/aleph/http.clj#L19
[imp]: https://github.com/ztellman/aleph/blob/df1cee3c4233c05fb27af62e9e2844bf453c70a9/src/aleph/http/server.clj#L399

**Comment by tomekw** [comment]
@MichaelBlume @ikitommi @jstepien just a thought: are https://github.com/MichaelBlume/hikari-cp/blob/2515b0cf73c3e45f5d64134b21200821055ccdd5/src/hikari_cp/core.clj#L117-L125 still needed?

@MichaelBlume could you also update CHANGELOG, please?

**Comment by ikitommi** [comment]
Do you mean, that the library would not set any values (or defaults) by itself, just would provide the Hook? Not much left here in that case.

I think most systems are configured with Clojure maps (read directly from edn-files, system props etc.) and not supporting map-based configuration would mean all the plumbing from maps to java methdos would fall back to the clients.

I would add support to all know configuration options via the options-map, backed by the Schema.

**Comment by jstepien** [comment]
> @MichaelBlume could you also update CHANGELOG, please?

Done in d5b2668b89044cf73ada41a22e6134ca707b78aa.

**Comment by tomekw** [comment]
:+1:

**Pull request merged**
