### PR TITLE
updated datasource examples to use delay

### PR DESCRIPTION
**Pull request by yogthos**

### CODE REVIEW

**Comment by jstepien** [comment]
Thanks a lot! Just a single small nitpick from my side.

**Comment by yogthos** [comment]
No problem, what was the nitpick? :)

**Comment by jstepien** [comment]
Just this single call to undefined `connect!` [over here](https://github.com/tomekw/hikari-cp/pull/80/files#diff-04c6e90faac2675aa89e2176d2eec7d8R121).

**Comment by yogthos** [comment]
oops fixed

**Comment by jstepien** [comment]
Lovely, thanks for improving all those code samples. Always a pleasure to merge another patch from you, Dmitri.

Closes #79.

**Comment by yogthos** [comment]
Any time, and thanks for a great library :-)

**Comment by tomekw** [comment]
Thanks @yogthos

**Pull request merged**
