### PR TITLE
Add another adapter to data source mapping for fdbsql.

### PR DESCRIPTION
**Pull request by MMcM**

### CODE REVIEW

**Comment by tomekw** [comment]
@MMcM could you also update the changelog with version `0.13.0` and entry:

"added support for FoundationDB driver (`:adapter` set to `fdbsql`)"

**Comment by MMcM** [comment]
Easy enough.

**Comment by tomekw** [comment]
Thanks!

**Comment by tomekw** [comment]
@MMcM I've released `0.13.0`. Feel free to mark `fdbsql` as tested in the README.

**Pull request merged**
