### PR TITLE
make option naming more consistent

### LINKED ISSUE #46: inconsistent naming of options
`:datasource-classname` and `:driver-class-name` are inconsistently formatted.

### PR DESCRIPTION
**Pull request by jjl**
transforms `:datasource-classname` -> `:datasource-class-name` while continuing to accept the old name.

Fixes #46 . Sorry about the delay, i haven't been writing much clojure recently.

### CODE REVIEW

**Comment by tomekw** [comment]
Thank you @jjl ! Could you also upgrade the CHANGELOG and the README?

**Comment by jjl** [comment]
No, that's your job.

**Comment by tomekw** [comment]
@jjl to me, the complete PR consists of: code changes, tests, documentation (if necessary), and CHANGELOG update. Could you, please, take care of this? 😄

**Comment by jjl** [comment]
Consider it taken care of.

**Pull request closed without merging**
