### PR TITLE
Fixes #56: support Healthcheck from DropWizard Metrics

### LINKED ISSUE #56: Support DropWizard Health Check
hikari-cp already supports DropWizard Metrics. 
It would be great if it also supported the healthcheck features.

### PR DESCRIPTION
**Pull request by rorygibson**
Add support for DropWizard Metrics Healthcheck functionality.
Implemented in the same way as the Metrics base support.

### CODE REVIEW

**Comment by tomekw** [comment]
Looks great to me! 👏 👏 @jstepien anything to add?

**Comment by tomekw** [comment]
@rorygibson one more thing - could you update the CHANGELOG too, please? :)

**Comment by jstepien** [comment]
Thanks for the patch, @rorygibson. We'll be happy to merge as soon as you update the changelog.

**Comment by tomekw** [comment]
Thank you @rorygibson. I hope I will have time to release it soon! :)

**Pull request merged**
